### ISSUE TITLE
YANG catalog impact analysis: apparent not working

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/yangcatalog-ui#27]
https://yangcatalog.org/yang-search/impact_analysis
I cut/paste my module: "ietf-x509-cert-to-name"
HOWEVER, I don't click on the proposed choice "ietf-x509-cert-to-name"
In this case, I can still click on "show impact analysis" but it takes forever, as if my choice was not taken into account.
Is this the expected behavior? Are we supposed to select the exact YANG module(s) before clicking "show impact analysis"? Or can I insert any free form text and the tool does a lookup in the background?

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I transfered this issue to yangcatalog-ui, because this seems to be UI bug. In fact, after clicking to Show Impact analysis button without selecting from proposed list it only looks like something is fetching from BE (because of loader icon ...). However no request is sent.
Expected behavior is that user selects one or more choices from selection list and then impact analysis is displayed. User should not be able to display analysis without selecting at least one option. I will try to fix this UI problem ASAP.

Regards,
Slavomir Mazur
