### ISSUE TITLE
What is a Sensor Path in Yang Catalog model tree view?

### ISSUE THREAD

**Issue by hellt** [YangCatalog/yangcatalog-ui#59]
Hi, sorry if this is a non appropriate project.
I wonder what information is contained within **Sensor Path** column that is present in some models
For example https://yangcatalog.org/yang-search/yang_tree/openconfig-platform@2022-02-02

This looks to me like some vendor specific path?

**Comment by SlavomirMazurPantheon** [comment]
Hello,

the explanation of the sensor path should be described here:
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/telemetry/b-telemetry-cg-asr9000-62x/b-telemetry-config-guide-asr9000_chapter_010.html#id_36273

Unfortunately, I do not have more detailed information, because from the programming point of view (which I am responsible for) difference between _path_ and _sensor path_ is that _path_ uses the module prefix while _sensor path_ uses the module name.

Regards,
Slavomir Mazur

**Comment by hellt** [comment]
thanks @SlavomirMazurPantheon 
would be nice to provide a description for that column, since this is a single vendor-specific path option.
